<?php
/**
 * @file
 * Code for the Growroom Agents feature.
 */

include_once 'growroom_agents.features.inc';

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_agents_growroom_ui_entities() {
  return array(
    'growroom_asset' => array(
      'agents' => array(
        'label' => t('Agents'),
        'label_plural' => t('Agents'),
        'view' => 'growroom_agents',
      ),
    ),
    'log' => array(
      'growroom_agent' => array(
        'label' => t('Agent'),
        'label_plural' => t('Agent'),
        'view' => 'growroom_log_agent',
        'growroom_asset' => 'agents',
        'weight' => 20,
      ),
    ),
  );
}

/**
 * Implements hook_growroom_log_categories().
 */
function growroom_agents_growroom_log_categories() {

  // Provide an "Agents" log category.
  return array('Agents');
}

/**
 * Implements hook_growroom_log_categories_populate().
 */
function growroom_agents_growroom_log_categories_populate($log) {
  $categories = array();
  if ($log->type == 'growroom_agent') {
    $categories[] = 'Agents';
  }
  return $categories;
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function growroom_agents_feeds_importer_default_alter($importers) {

  // Add extra field mappings to agents.
  $name = 'growroom_asset_agents';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Alias',
        'target' => 'field_growroom_alias',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Species',
        'target' => 'field_growroom_agents_species',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Brand',
        'target' => 'field_growroom_brand',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Source',
        'target' => 'field_growroom_source',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Purchase Date',
        'target' => 'field_growroom_date:start',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Type',
        'target' => 'field_growroom_type',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Lot Size',
        'target' => 'field_growroom_lot_size',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Specifications',
        'target' => 'field_growroom_specifications',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Purpose',
        'target' => 'field_growroom_purpose',
        'unique' => FALSE,
        'language' => 'und',
      ),  
      array(
        'source' => 'Method',
        'target' => 'field_growroom_method',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Storage',
        'target' => 'field_growroom_storage',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Shelf Life',
        'target' => 'field_growroom_shelf_life',
        'unique' => FALSE,
        'language' => 'und',
      ),  
      array(
        'source' => 'Warnings',
        'target' => 'field_growroom_warnings',
        'unique' => FALSE,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}
