<?php
/**
 * @file
 * Code for the Growroom Log: Observation feature.
 */

// Include Features code.
include_once 'growroom_log_observation.features.inc';

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_log_observation_growroom_ui_entities() {
  return array(
    'log' => array(
      'growroom_observation' => array(
        'label' => t('Observation'),
        'label_plural' => t('Observations'),
        'view' => 'growroom_log_observation',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}
