<?php
/**
 * @file
 * Code for the Growroom Seeds feature.
 */

include_once 'growroom_seeds.features.inc';

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_seeds_growroom_ui_entities() {
  return array(
    'growroom_asset' => array(
      'seeds' => array(
        'label' => t('Seeds'),
        'label_plural' => t('Seeds'),
        'view' => 'growroom_seeds',
      ),
    ),
    'log' => array(
      'growroom_seed' => array(
        'label' => t('Seed'),
        'label_plural' => t('Seed'),
        'view' => 'growroom_log_seed',
        'growroom_asset' => 'seeds',
        'weight' => 20,
      ),
    ),
  );
}

/**
 * Implements hook_growroom_log_categories().
 */
function growroom_seeds_growroom_log_categories() {

  // Provide an "Seeds" log category.
  return array('Seeds');
}

/**
 * Implements hook_growroom_log_categories_populate().
 */
function growroom_seeds_growroom_log_categories_populate($log) {
  $categories = array();
  if ($log->type == 'growroom_seed') {
    $categories[] = 'Seeds';
  }
  return $categories;
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function growroom_seeds_feeds_importer_default_alter($importers) {

  // Add extra field mappings to seeds.
  $name = 'growroom_asset_seeds';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Alias',
        'target' => 'field_growroom_cultivar',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Purchase Date',
        'target' => 'field_growroom_date:start',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Brand',
        'target' => 'field_growroom_brand',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Source',
        'target' => 'field_growroom_source',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Model',
        'target' => 'field_growroom_lot',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Purpose',
        'target' => 'field_growroom_specifications',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Method',
        'target' => 'field_growroom_method',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Storage',
        'target' => 'field_growroom_storage',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Shelf Life',
        'target' => 'field_growroom_shelf_life',
        'unique' => FALSE,
        'language' => 'und',
      ),  
      array(
        'source' => 'Warnings',
        'target' => 'field_growroom_warnings',
        'unique' => FALSE,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}
