<?php
/**
 * @file
 * Code for the Growroom Consumables feature.
 */

include_once 'growroom_consumables.features.inc';

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_consumables_growroom_ui_entities() {
  return array(
    'growroom_asset' => array(
      'consumables' => array(
        'label' => t('Consumables'),
        'label_plural' => t('Consumables'),
        'view' => 'growroom_consumables',
      ),
    ),
    'log' => array(
      'growroom_consumables' => array(
        'label' => t('Consumables'),
        'label_plural' => t('Consumables'),
        'view' => 'growroom_log_consumables',
        'growroom_asset' => 'consumables',
        'weight' => 20,
      ),
    ),
  );
}

/**
 * Implements hook_growroom_log_categories().
 */
function growroom_consumables_growroom_log_categories() {

  // Provide an "Consumables" log category.
  return array('Consumables');
}

/**
 * Implements hook_growroom_log_categories_populate().
 */
function growroom_consumables_growroom_log_categories_populate($log) {
  $categories = array();
  if ($log->type == 'growroom_consumables') {
    $categories[] = 'Consumables';
  }
  return $categories;
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function growroom_consumables_feeds_importer_default_alter($importers) {

  // Add extra field mappings to consumables.
  $name = 'growroom_asset_consumables';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Alias',
        'target' => 'field_growroom_alias',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Brand',
        'target' => 'field_growroom_brand',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Source',
        'target' => 'field_growroom_source',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Model',
        'target' => 'field_growroom_model',
        'unique' => FALSE,
        'language' => 'und',  
      ),
      array(
        'source' => 'Specifications',
        'target' => 'field_growroom_specifications',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Purpose',
        'target' => 'field_growroom_purpose',
        'unique' => FALSE,
        'language' => 'und',
      ),  
      array(
        'source' => 'Method',
        'target' => 'field_growroom_method',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Storage',
        'target' => 'field_growroom_storage',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Shelf Life',
        'target' => 'field_growroom_shelf_life',
        'unique' => FALSE,
        'language' => 'und',
      ),  
      array(
        'source' => 'Warnings',
        'target' => 'field_growroom_warnings',
        'unique' => FALSE,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}
