version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - './.data/db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: growroomos
      MYSQL_DATABASE: growroomos
      MYSQL_USER: growroomos
      MYSQL_PASSWORD: growroomos

  www:
    depends_on:
      - db
    image: growroomos/growroomos:7.x-1.0-rc1
#    image: growroomos/growroomos:7.x-1.x
    volumes:
      - './.data/www:/var/www/html'
    links:
      - db
    ports:
      - '80:80'
    environment:
      GROWROOMOS_DEV: 'true'
