<?php
/**
 * @file
 * Code for the Growroom Environment feature.
 */

include_once 'growroom_environment.features.inc';

/**
 * Implements hook_help().
 */
function growroom_environment_help($path, $arg) {

  // Add help text to the environment plan list page.
  if ($path == 'growroom/plans/environment') {
    $help = '<p>' . t("This page lists all environment management plans. Select one from the list below to view it, or click \"Add environment management plan\" to create a new one.") . '</p>';
    $help .= '<p>' . t("Plans can be archived for future reference. To view archived plans, use the \"Filter/sort\" options in the list below.") . '</p>';
    return $help;
  }

  // If the path starts with 'growroom/plan/%', then load the plan and see if it is
  // a environment plan. If not, bail. Otherwise continue.
  if (strpos($path, 'growroom/plan/%') === 0) {
    $plan = growroom_plan_load($arg[2]);
    if (empty($plan) || $plan->type != 'environment') {
      return '';
    }
  }

  // Add help text to all growroom/plan/% paths.
  switch ($path) {

    // Plan add/edit form.
    case 'growroom/plan/add/environment':
    case 'growroom/plan/%/edit':
      $help = '<p>' . t('Use the form below to define the specifics for this environment management plan.') . '</p>';
      $help .= '<p>' . t('A plan has a name, a date range, a season (optional), and any additional notes you want to include. You can reference the areas that this plan pertains to.') . '</p>';
      $help .= '<p>' . t('Upload your environment management planning files and documents to the "Files" field for easy reference.') . '</p>';
      return $help;

    // Plan view page.
    case 'growroom/plan/%':
    case 'growroom/plan/%/view':
      $help = '<p>' . t('This page summarizes the details of this environment management plan.') . '</p>';
      $help .= '<p>' . t('To edit the plan, click the "Settings" tab.') . '</p>';
      return $help;
  }
}

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_environment_growroom_ui_entities() {
  return array(
    'growroom_plan' => array(
      'environment' => array(
        'label' => t('Environment Management Plan'),
        'label_plural' => t('Environment Management Plans'),
        'view' => 'growroom_environment_plan',
      ),
    ),
  );
}

/**
 * Implements hook_bootstrap_iconize_text_alter().
 */
function growroom_environment_bootstrap_iconize_text_alter(&$texts) {

  // The Bootstrap theme automatically adds a cog icon to buttons that contain
  // the string "manage", so we need to explicitly override that here to use
  // the plus icon (for consistency with other buttons that begin with "Add").
  $texts['matches'][t('Add environment management plan')] = 'plus';
}
