<?php
/**
 * @file
 * Code for the Growroom Light Test feature.
 */

include_once 'growroom_light_test.features.inc';

/**
 * Implements hook_help().
 */
function growroom_light_test_help($path, $arg) {
  if ($path == 'log/add/growroom_light_test') {
    $help = '<p>' . t('Use this form to enter information about light tests you have performed. Use the log date field to record when the light sample was taken. Test results can be uploaded to the files field as a PDF or other document.') . '</p>';
    $help .= '<p>' . t('Each sample/test can be entered as a separate log, for easier searching/filtering later. Or, if you have a document from your lab that contains results of multiple tests, you can upload that to a single log for general storage. Give it a relative date based on when the samples were taken so that you can find it by month or year.') . '</p>';
    return $help;
  }
}

/**
 * Implements hook_growroom_ui_entities().
 */
function growroom_light_test_growroom_ui_entities() {
  return array(
    'log' => array(
      'growroom_light_test' => array(
        'label' => t('Light test'),
        'label_plural' => t('Light tests'),
        'view' => 'growroom_log_light_tests',
        'growroom_asset' => 'none',
        'areas' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_growroom_log_categories_populate().
 */
function growroom_light_test_growroom_log_categories_populate($log) {
  $categories = array();
  if ($log->type == 'growroom_light_test') {
    $categories[] = 'Light';
  }
  return $categories;
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function growroom_light_test_feeds_importer_default_alter(&$importers) {

  // Add extra field mappings to light tests.
  $name = 'log_growroom_light_test';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Laboratory',
        'target' => 'field_growroom_light_lab',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Light names',
        'target' => 'field_growroom_light_names',
        'term_search' => '0',
        'autocreate' => 1,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}

/**
 * Implements hook_feeds_tamper_default_alter().
 */
function growroom_light_test_feeds_tamper_default_alter(&$feeds_tampers) {

  // If growroom_import is not installed, bail.
  if (!module_exists('growroom_import')) {
    return;
  }

  // Explode light names so it supports multiple values.
  $feeds_tamper = growroom_import_feeds_tamper_plugin('log', 'growroom_light_test', 'Light names', 'explode');
  $feeds_tampers[$feeds_tamper->id] = $feeds_tamper;
}
